# Generated by Django 4.2 on 2024-10-09 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msa', '0002_rename_client_id_msa_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0002_alter_contractstatus_options'),
        ('sow', '0002_alter_sowtype_sow_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.CharField(max_length=4)),
                ('invoice_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('fortnightly', 'Fortnightly')], default='monthly', max_length=100)),
                ('next_due_renewal', models.DateField()),
                ('sow_doc_path', models.FileField(upload_to='sow_docs')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_for_sow', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_for_sow', to=settings.AUTH_USER_MODEL)),
                ('msa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msa.msa')),
                ('sow_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sow.sowtype')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractstatus')),
            ],
            options={
                'verbose_name': 'SOW',
                'verbose_name_plural': 'SOWs',
            },
        ),
    ]
