# Generated by Django 4.2 on 2024-10-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sow', '0003_sow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sow',
            name='client',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_for_sow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sow',
            name='sow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sow.sowtype'),
        ),
    ]
