# Generated by Django 4.2 on 2024-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentapproval',
            name='action_at',
            field=models.DateTimeField(null=True),
        ),
    ]
