# Generated by Django 4.2 on 2024-10-17 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_approval', '0002_alter_documentapproval_action_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentapproval',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='assigned_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
