# Generated by Django 4.2 on 2024-10-17 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_approval', '0003_remove_documentapproval_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentapproval',
            unique_together={('object_id', 'content_type', 'assigned_to')},
        ),
        migrations.RemoveField(
            model_name='documentapproval',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
