# Generated by Django 4.2 on 2024-09-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_user_id_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Organization',
            name='organization_address',
            field=models.TextField(),
        ),
    ]
