# Generated by Django 4.2 on 2024-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_organization_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('vender', 'Vender'), ('organization', 'Organization')], default='organization', max_length=100),
        ),
    ]
