# Generated by Django 4.2 on 2024-09-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractstatus',
            options={'verbose_name_plural': 'Contract Status'},
        ),
    ]
